tripohoolic/common/urls.py
from django.urls import path

from tripohoolic.common.views import index, dashboard, comment_trip, rate_trip, delete_comment

urlpatterns = [
    path('', index, name='index'),
    path('dashboard/', dashboard, name='dashboard'),
    path('comment/<int:trip_id>/', comment_trip, name='comment trip'),
    path('rate/<int:trip_id>/', rate_trip, name='rate trip'),
    path('comment/delete/<int:comment_id>/', delete_comment, name='delete comment'),

]

tripohoolic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tripohoolic.common.urls')),
    path('accounts/', include('tripohoolic.accounts.urls')),
    path('trips/', include('tripohoolic.trips.urls')),
    path('agencies/', include('tripohoolic.agencies.urls')),

    #Enable browsable API of Django Rest Framework
    path('api-auth/', include('rest_framework.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tripohoolic/common/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import Avg

from tripohoolic.trips.models import Trips

UserModel = get_user_model()


class TripComment(models.Model):
    MAX_TEXT_LENGTH = 333

    text = models.CharField(
        max_length=MAX_TEXT_LENGTH,
        null=False,
        blank=False,
    )

    publication_date_and_time = models.DateTimeField(
        auto_now_add=True,
        blank=True,
        null=False,
    )

    trip = models.ForeignKey(
        Trips,
        on_delete=models.CASCADE,
        null=False,
        blank=True,
    )

    user = models.ForeignKey(
        UserModel,
        on_delete=models.DO_NOTHING,
    )


class TripRating(models.Model):
    RATES = (
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
    )

    trip = models.ForeignKey(
        Trips,
        on_delete=models.CASCADE,
        null=False,
        blank=True,
    )

    user = models.ForeignKey(
        UserModel,
        on_delete=models.DO_NOTHING,
    )

    rate = models.PositiveIntegerField(
        choices=RATES,
    )

    #Data for the calculation is here (TripRating) and the field 'average_rating' is in Trips
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        # Calculate and update the average rating in the related Trips instance
        average_rating = TripRating.objects.filter(trip=self.trip).aggregate(Avg('rate'))['rate__avg']
        self.trip.average_rating = average_rating
        self.trip.save()

tripohoolic/common/forms.py
from django import forms

from tripohoolic.common.models import TripComment, TripRating


class TripCommentForm(forms.ModelForm):
    class Meta:
        model = TripComment
        fields = ('text',)
        widgets = {
            'text': forms.TextInput(
                attrs={
                    'placeholder': 'Please enter your comment',
                },
            ),
        }

        labels = {
            'text': "Comment",
        }


class TripRatingForm(forms.ModelForm):
    class Meta:
        model = TripRating
        fields = ('rate',)


class SearchCountryForm(forms.Form):
    country_name = forms.CharField(
        max_length=20,
        required=False,
    )


class SearchCityForm(forms.Form):
    city_name = forms.CharField(
        max_length=20,
        required=False,
    )

tripohoolic/common/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.db.models import Avg
from django.shortcuts import render, redirect

from tripohoolic.common.forms import TripCommentForm, TripRatingForm, SearchCountryForm, SearchCityForm
from tripohoolic.common.models import TripComment, TripRating
from tripohoolic.trips.models import Trips
from django_countries import countries

UserModel = get_user_model()


def map_country_name(name, to_abbreviation=True):
    if to_abbreviation:
        for code, country_name in countries:
            if country_name.lower() == name.lower():
                return code
    else:
        for code, country_name in countries:
            if code.lower() == name.lower():
                return country_name

    print(f"No abbreviation found for country: {name}")
    return None


def index(request):
    trips = Trips.objects.all()

    search_form_country = SearchCountryForm(request.GET)
    search_pattern = None
    if search_form_country.is_valid():
        search_pattern = search_form_country.cleaned_data['country_name']

    if search_pattern:
        # Convert the full country name to abbreviation
        country_abbreviation = map_country_name(search_pattern)
        if country_abbreviation:
            trips = trips.filter(country__icontains=country_abbreviation)

    # search_form_city = SearchCityForm(request.GET)
    # search_pattern = None
    # if search_form_city.is_valid():
    #     search_pattern = search_form_city.cleaned_data['city_name']
    #
    # if search_pattern:
    #     trips = trips.filter(city__icontains=search_pattern)

    authenticated_user = request.user.is_authenticated

    context = {
        'trips': trips,
        'comments_form': TripCommentForm(),
        'rate_form': TripRatingForm(),
        'search_form_country': SearchCountryForm(),
        'search_form_city': SearchCityForm(),
        'authenticated_user': authenticated_user,
    }
    return render(request, 'common/index.html', context)


@login_required
def dashboard(request):
    logged_in_user = request.user
    trips = Trips.objects.all().filter(user=logged_in_user)

    context = {
        "profile": logged_in_user,
        'trips': trips,
    }
    return render(request, 'common/dashboard.html', context)


@login_required
def comment_trip(request, trip_id):
    trip = Trips.objects.get(pk=trip_id)

    form = TripCommentForm(request.POST)

    if form.is_valid():
        comment = form.save(commit=False)  # Does not persist to DB ... Do not save it to DB
        comment.trip = trip  # Takes trip by trip_in
        comment.user_id = request.user.id
        comment.save()

    return redirect('index')


@login_required
def delete_comment(request, comment_id):
    TripComment.objects.get(pk=comment_id).delete()
    return redirect('index')


@login_required
def rate_trip(request, trip_id):
    rating_trip = Trips.objects.get(pk=trip_id)

    try:
        existing_rating = TripRating.objects.get(trip_id=trip_id, user_id=request.user.id)
        existing_rating.delete()
    except TripRating.DoesNotExist:
        pass

    form = TripRatingForm(request.POST)

    if form.is_valid():
        rate = form.save(commit=False)
        rate.trip_id = rating_trip.pk
        rate.user_id = request.user.id
        rate.save()

    return redirect('index')

templates/common/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=\, initial-scale=1.0"/>
    <link rel="stylesheet" href="{% static 'styles/styles.css' %}"/>
    <style>
        form.helptext {
            font-size: 0.7em;
        }
    </style>

    <title>Tripohoolic</title>
</head>
<body>
<div id="wrapper">
    <header>
        <!-- Navigation -->
            <a id="logo" href="{% url 'index' %}">
                <img id="logo-img" src="{% static 'images/logo2.png' %}" alt="logo"/>
            </a>

        <nav>
            <div class="nav-links">
                <ul class="nav-group">
                    {% if request.user.is_authenticated %}
                        <div class="user">
                            <a href="{% url 'details user' pk=request.user.pk %}"><i>{{ request.user.username }}</i></a>
                            <a href="{% url 'dashboard' %}"><i>My Trips</i></a>
                            <a href="{% url 'agencies' %}"><i>Agencies</i></a>
                            <a href="{% url 'create trip' %}"><i>Create Trip</i></a>
                            <a href="{% url 'logout user' %}"><i>Logout</i></a>
                        </div>
                    {% else %}

                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>

    {% block content %}
    {% endblock %}

    <footer>
        <p>@Tripohoolic.</p>
    </footer>
</div>
</body>
</html>

templates/common/dashboard.html
{% extends 'common/base.html' %}
{% load static %}

{% block content %}

    <main>
        <!-- Dashboard Page -->
        <h1>My Trips</h1>
        {% if trips %}
            <section id="dashboard">
                {% for trip in trips %}
                    <div class="trip">
                        <p><b><u>Trip name:</u></b> {{ trip.trip_name }}</p>
                        <p><b><u>Trip type:</u></b> {{ trip.type }}</p>
                        {% if trip.type == "Agency" %}
                            <p><b><u>Agency:</u></b> {{ trip.used_agency }}</p>
                        {% endif %}
                        <p><b><u>Country:</u></b> {{ trip.country.name }}</p>
                        <p><b><u>Cities:</u></b> {{ trip.cities }}</p>
                        <p><b><u>Rating:</u></b> {{ trip.average_rating }}</p>

                        <a class="details-btn" href="{% url 'details trip' pk=trip.pk %}">More Details</a>
                    </div>
                {% endfor %}
            </section>
        {% else %}
            <h2>No trips yet.</h2>
        {% endif %}
    </main>

{% endblock %}

templates/common/index.html
{% extends 'common/base.html' %}
{% load static %}

{% block content %}

    <main>
        {% if authenticated_user %}
            <!-- Start Searchbar Form -->
            <form class="searchbar" method="get" action="{% url 'index' %}">
                {{ search_form_country }}
                <button>
                    <img src="{% static 'images/search_icon.png' %}" height="12" alt="img2">
                </button>
                {% csrf_token %}
            </form>
            <!-- End Searchbar Form -->
        {% endif %}


        <!-- Home page -->
        {% if not authenticated_user %}
            <p id="website-title">Do you want to take advice and share you passion about travelling.. come and join us
                by creating an
                account..
            </p>
            <p id="website-title">
                <a href="{% url 'register user' %}"><i>Register</i></a>
                ... or ...
                <a href="{% url 'login user' %}"><i>Login</i></a>
            </p>
        {% endif %}

        {% for trip in trips %}
            <div id="details-wrapper">

                {#                <img id="details-img" src="{{ trip.image_url }}" alt="trip_photo"/>#}

                <p><b><u>User: </u></b><a href="{% url 'details user' pk=trip.user.pk %}">{{ trip.user.username }}</a></p>
                <p><b><u>Trip name:</u></b> {{ trip.trip_name }}</p>
                <p><b><u>Trip type:</u></b> {{ trip.type }}</p>
                {% if trip.type == "Agency" %}
                    <p><b><u>Agency:</u></b> {{ trip.used_agency }}</p>
                {% endif %}
                <p><b><u>Country:</u></b>
                     {% for country in trip.country%}
                        {{ country.name }},
                        {% endfor %}
                </p>
                <p><b><u>Cities:</u></b> {{ trip.cities }}</p>
                <p><b><u>Rate:</u></b> {{ trip.average_rating }}</p>

                {% if authenticated_user %}
                    <div>
                        <a class="details-btn" href="{% url 'details trip' pk=trip.pk %}">More Details</a>

                        <!--Rating section -->
                        {% include 'common/trip_rating.html' with trip=trip %}

                        <!--Comments section -->
                        {% include 'common/trip_comment.html' with trip=trip %}
                    </div>
                {% endif %}
                <p><b><u>Photos:</u></b></p>
                {% for photo in trip.photos.all %}
                    <img id="details-img" src="{{ photo.image.url }}"/>
                {% endfor %}

            </div>
        {% endfor %}

    </main>
{% endblock %}

templates/common/trip_comment.html
<h2>Comments</h2>
<div class="comments-section">

    <div class="posted-comments">
        {% if trip.tripcomment_set.all %}
            {% for comment in trip.tripcomment_set.all %}
                <div class="comment">

                    <div class="comment-author"><a
                            href="{% url 'details user' pk=request.user.pk %}">{{ comment.user }}</a>
                    </div>

                    <!-- Delete my comment -->
                    <div class="comment-text">{{ comment.text }}</div>
                    {% if comment.user == request.user %}
                    <form method="post" action="{% url 'delete comment' comment_id=comment.id %}">
                        <button type="submit">x</button>
                        {% csrf_token %}
                    </form>
                    {% endif %}

                </div>
            {% endfor %}
        {% else %}
            No comments yet.
        {% endif %}
    </div>
</div>

<!-- Add comments -->
<div class="add-comment">
    <h2>Add Comment</h2>
    <div class="comment">
        <form method="post" action="{% url 'comment trip' trip_id=trip.pk %}">
            {{ comments_form.as_table }}

                <button type="submit">Post</button>

            {% csrf_token %}
        </form>
    </div>
</div>

templates/common/trip_rating.html
{% load tags %}

<h4>Rate this trip:</h4>
<div class="rate-section">

    My rating: {% my_rating trip_id=trip.pk user_id=user.pk%}

    <form class="create-form" method="post" action="{% url 'rate trip' trip_id=trip.pk %}">
        {{ rate_form }}

        <button type="submit">Rate</button>

        {% csrf_token %}
    </form>
</div>